pointcloud_listener_node:
  ros__parameters:
    source_pcl_topic: "/cloud_registered_body"
    dynamic_pcl_topic: "/cloud_dynamic_body"
    pcl_frame: "os_lidar"
    dynablox_param_path: "/root/install/dynablox/assets/config.yaml" # Only works in provided container!
