

# ----------- Motion Detector Parameters --------
# General.
num_threads: 24
verbose: false

# Preprocessing.
preprocessing:
  min_range: 0.5  # m
  max_range: 10  # m

# Ever-Free Integration.
ever_free_integrator:
  counter_to_reset: 150 # Observations to un-free an ever-free voxel [frames]
  temporal_buffer: 2   # To compensate sparsity [frames].
  burn_in_period: 5   # Burn in before becoming ever-free [frames].
  tsdf_occupancy_threshold: 0.15 # 1.5 voxel sizes.
  neighbor_connectivity: 26
  
# Clustering.
clustering:
  min_cluster_size: 20
  max_cluster_size: 200000
  min_extent: 0   # m
  max_extent: 200000   # m
  neighbor_connectivity: 6
  check_cluster_separation_exact: false
  grow_clusters_twice: false
  min_cluster_separation: 0.2
  
# Tracking.
tracking:
  min_track_duration: 0 # frames
  max_tracking_distance: 1  # m

# Voxblox parameters.
voxblox:
  # SDF.
  tsdf_voxel_size: 0.05
  truncation_distance: 0.4
  tsdf_voxels_per_side: 16
  max_weight: 1000
  
  # Integration.
  method: projective
  sensor_horizontal_resolution: 2048
  sensor_vertical_resolution: 64
  sensor_vertical_field_of_view_degrees: 33.22222
  use_const_weight: true
